#!/bin/bash

resPos=7
resStr='D1'
pattern=" D   ${resPos}.*${resStr}"

while read -r line 
do

	if [[ $line =~ $pattern ]] && [[ "$resPos" -gt 6 ]]
	then
        echo 'higher'
	fi

done < NRAS-DBahA-AVG-STR.pdb