#!/bin/bash

resOld=$1
resPos=$2
resNew=$3
#make later resTLC=$1$3H
resStr="$4"
#residue end = $($2 +_ 1)
penultimateLine=$(tail -2 NRAS-DBahA-AVG-STR.pdb | head -n 1)
penultimateArray=($penultimateLine)

resN=penultimateArray[5] #Total number of residues in the file
compPos="$(($resN + 1 - $resPos))"


#Determines the complement base's strand
if [ $resStr = 'D1' ]
    then compStr='D2'
else compStr='D1'
fi


#Determines complement's identity
if [[ $resNew = 'A' ]]; then compNew='T'
elif [[ $resNew = 'T' ]]; then compNew='A'
elif [[ $resNew = 'G' ]]; then compNew='C'
elif [[ $resNew = 'C' ]]; then compNew='G'; fi


#The following creates our Chimera script that then creates the single-top-step1 pdb file
cat << END > swapna.com
swapna ${resNew} :${resPos} & @/pdbSegment=${resStr}
sel :${resPos} & @/pdbSegment=${resStr}
addh
swapna ${compNew} :${compPos} & @/pdbSegment=${compStr}
sel :${compPos} & @/pdbSegment=${compStr}
addh
write format pdb #0 NRAS-DBahA-single-top-step1.pdb
END

chimera --nogui --silent NRAS-DBahA-AVG-STR.pdb swapna.com